apiVersion: v1
kind: Service
metadata:
  name: go-backend
  namespace: zk-identity
  labels:
    app.kubernetes.io/name: go-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: go-backend
    app.kubernetes.io/component: backend
